spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/audit_db
    username: '{cipher}172fc0d9ddab31d355de8125135163fff01d1ac7da9d88aa860a0140306f4b90' #encrypt
    password: '{cipher}ef0fc7cc0e35bf2ff973d12714b74060dac106faadd8c5846a06e35ca83a89f4' #encrypt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        format_sql: true
        show_sql: false

server:
  port: 3000

management:
  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://${JAEGER_HOST:jaeger}:4318/v1/traces

  otlp:
    metrics:
      export:
        enabled: false