spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vault_db
    username: '{cipher}e987d1885282c7ed3647b71625204a76231261701ff4acd6a832375bea55157d' #encrypt
    password: '{cipher}d9dd119982039b8a8514e3744b41129e80ab62e6d47bff0f13efe87a46cdd632' #encrypt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://${JAEGER_HOST:jaeger}:4318/v1/traces

  otlp:
    metrics:
      export:
        enabled: false

  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 3001