spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C

  otlp:
    tracing:
      endpoint: http://${JAEGER_HOST:jaeger}:4318/v1/traces
    metrics:
      export:
        enabled: false

  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 3001
